#!/bin/bash
#
# This script puts together a .deb package suitable for installing on an Ubuntu
# system

B="/tmp/sshuttle/build"

# Make sure we're in the current working directory, as some things require it
if [ ! -x "./$(basename "$0")" ]; then
	echo 'Unable to build: need to be in the packaging directory of sshuttle where this script lives' > /dev/stderr
	exit 1
fi

if [ ! -x /usr/bin/dpkg ]; then
	echo 'Unable to build: dpkg not found on system' > /dev/stderr
	exit 1
fi

# Create the new directory structure
mkdir -p ${B}/etc/sshuttle/pre-start.d
mkdir -p ${B}/etc/sshuttle/post-stop.d
mkdir -p ${B}/usr/share/sshuttle/scripts
mkdir -p ${B}/usr/bin
mkdir -p ${B}/lib/systemd/system
mkdir -p ${B}/DEBIAN

# Copy over all of the files
cp -r ../src/* ${B}/usr/share/sshuttle
cp ../src/sshuttle ${B}/usr/bin
cp -r sshuttle.conf ${B}/etc/init
cp prefixes.conf.dist ${B}/etc/sshuttle
cp tunnel.conf.dist ${B}/etc/sshuttle

# Copy over all of the scripts / installers
cp sshuttle-pre-start.sh ${B}/usr/share/sshuttle/scripts
cp sshuttle-post-stop.sh ${B}/usr/share/sshuttle/scripts
cp sshuttle.service ${B}/lib/systemd/system

# Copy the control files over, as well
cp control ${B}/DEBIAN
cp postinst ${B}/DEBIAN

# Delete out any .pyc files; not guaranteed to work here
find ${B} -type f -name '*.pyc' | xargs rm -f

# Get rid of the .gitignore file...
find ${B} -type f -name '*.gitignore' | xargs rm -f

# Create the md5sum manifest
if [ -x /usr/bin/md5sum ]; then
	cd ${B}
	find . -type f | egrep -v DEBIAN | sed -re 's/^..//' | xargs md5sum > ${B}/DEBIAN/md5sums
	cd ${OLDPWD}
fi

# Build the debian package
VERSION=$(egrep -e '^Version' control | sed -re 's/^[^:]*: //')
dpkg --build ${B} ./sshuttle-${VERSION}.deb
rm -rf ${B}
